### ISSUE TITLE
Xiant.Filer.3.VTSO did not download

### ISSUE THREAD

**Issue by beaudknows** [VulcanTechnologies/XiantFiler#2]
I recently tried to upgrade to the latest version. I am now receiving the following error when I open Outlook 2016 or a Win 10 machine. 
![xiant](https://cloud.githubusercontent.com/assets/14064941/16992071/f337bac8-4e6b-11e6-9eef-2b2a98fb5e0e.jpg)

**Comment by beaudknows** [comment]
You can disregard the above issue. I was able to correct by removing some registry keys.

**Comment by hickeys** [comment]
Thanks for letting us know. Glad it's working correctly for you.
